---
- name: Configure network interfaces
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: true
    owner: root
    group: root
    mode: 0644
  become: true
  notify: Restart network interfaces

- name: Configure network interface names
  ansible.builtin.template:
    src: link.j2
    dest: /etc/systemd/network/10-persistent_{{ item.ifname }}.link
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ pve_netif_alias }}"
  when: pve_netif_alias is defined
  become: true
  notify: Reboot host

- name: Force host reboot
  ansible.builtin.debug:
    msg: "pve_force_reboot was set to true. Rebooting the host"
  notify: Reboot host
  when: pve_force_reboot
