---
- name: Check system OS
  ansible.builtin.fail:
    msg: "Cannot Proceed. Expected Debian"
  when: ansible_distribution != "Debian"

- name: Install bridge-utils
  ansible.builtin.apt:
    name: 
      - bridge-utils
      - ifenslave
    state: present
    update_cache: true

- name: Configure networking
  ansible.builtin.include_tasks: config-network.yml
  when: pve_netif_alias is defined and pve_netif_bridges is defined
